package baidiuk;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser(@RequestParam String name,
                      @RequestParam String surName,
                      @RequestParam String phoneNumber,
                      @RequestParam String address,
                      @RequestParam String comment) {


        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Contact n = new Contact();

        n.setName(name);
        n.setSurName(surName);
        n.setPhoneNumber(phoneNumber);
        n.setAddress(address);
        n.setComment(comment);

        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Contact> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}